### PR TITLE
Fix #2: Create a readme file

### LINKED ISSUE #2: Add Readme.md file
I can write the readme.md file, please assign it to me and add the Hacktoberfest tag :)

### PR DESCRIPTION
**Pull request by shreyansh1410**
**Add Comprehensive README for Blogverse**

This pull request introduces a detailed README file for the Blogverse project. The new README provides information about the project setup, structure, and usage, making it easier for contributors and users to work with our MERN stack blog application.
Key additions:

- Project overview and features list
- Setup and installation instructions
- Running the app in development and production modes
- API endpoints overview
- Basic database schema
- Contributing guidelines

This update improves our project documentation and should help new developers get started more quickly.

Fixed #2

### CODE REVIEW

**Comment by shreyansh1410** [comment]
closes issue: #9

**Comment by Anshul439** [comment]
It's very long and there is some unnecessary stuff. Just add basic stuff like overview, features, Contributing guidelines, and basic setup

**Comment by shreyansh1410** [comment]
Okay, will look into it

**Comment by shreyansh1410** [comment]
I've updated with a new commit, please look into it

**Pull request merged**
