### PR TITLE
issue #10 :  Added 404 component and fallback route for undefined paths.

### PR DESCRIPTION
**Pull request by akshatshukla13**
issue #10
- Added 404 `PageNotFound` component for invalid routes.
- Set up fallback route for undefined paths.
- Responsive design.
- lightweight | No images used; focused on simple animations and text.

testt

### CODE REVIEW

**Comment by akshatshukla13** [comment]
Added `Dark theme` also.. it is synced with header's toggle button .

Capture

**Comment by Anshul439** [comment]
It's good. Just change the emoji.

**Comment by akshatshukla13** [comment]
Capture

**Comment by Anshul439** [comment]
Umm it's position is not looking good. Either change the position or maybe remove it. Will be fine without it.

**Comment by akshatshukla13** [comment]
The emoji is bouncing smoothly due to animations, and it looks really nice!

**Comment by akshatshukla13** [comment]
do i just remove it?

**Comment by Anshul439** [comment]
> The emoji is bouncing smoothly due to animations, and it looks really nice!

Can you show the recording of animation?

**Comment by akshatshukla13** [comment]
https://github.com/user-attachments/assets/528c7ee4-7237-4c0b-a3f0-c34a9ce634f2

**Comment by Anshul439** [comment]
It's good but I don't think it's needed here. Remove it and let me know.

**Comment by akshatshukla13** [comment]
Removed

**Pull request merged**
